project:
  type: website
  output-dir: _site

website:
  title: "abaleiv"
  navbar:
    search: true
    left:
      - href: about.qmd
        text: About
      - href: docs/blog/index.qmd
        text: Blog

comments:
  giscus:
    repo: bastianabaleiv/bastianabaleiv_website

format:
  html:
    theme:
      light: [cosmo, styles.scss, light.scss]
      dark: [cosmo, styles.scss, dark.scss]
    css: styles.css
    toc: true

execute: 
  freeze: auto


